//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduction
    {
        public int Id { get; set; }
        public int IdProduction { get; set; }
        public int IdOrder { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Production Production { get; set; }
    }
}
